DefaultContentLanguage = "en"
baseURL = "https://example.com"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en"
summarylength = 10
theme = "anatole"
title = "Website of Jane Doe"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 5
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/post/"
weight = 4
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/post/"
weight = 3
[[menu.main]]
identifier = "performance"
name = "Artistry"
url = "/artistry/"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[params]
author = "Jane Doe"
customCss = []
customJs = []
description = "Call me Jane"
doNotLoadAnimations = true
favicon = "favicons/"
images = ["images/site-feature-image.png"]
keywords = ""
mainSections = ["performance", "post"]
profilePicture = "images/profile.jpg"
title = "I'm Jane Doe"
[params.math]
enable = false
use = "katex"
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/lxndrblz/anatole/"
[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:mail@alexbilz.com"
